# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

version <- function() {
    .Call(`_V8_version`)
}

context_eval <- function(src, src_module, ctx, serialize = FALSE, await = FALSE) {
    .Call(`_V8_context_eval`, src, src_module, ctx, serialize, await)
}

write_array_buffer <- function(key, data, ctx) {
    .Call(`_V8_write_array_buffer`, key, data, ctx)
}

context_validate <- function(src, src_module, ctx) {
    .Call(`_V8_context_validate`, src, src_module, ctx)
}

context_null <- function(ctx) {
    .Call(`_V8_context_null`, ctx)
}

make_context <- function(set_console) {
    .Call(`_V8_make_context`, set_console)
}

