# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Validate and evaluate JavaScript code
#'
#' The \code{jsvalidate} function tests if a string is valid JavaScript.
#' The \code{jseval} function evaluates a JavaScript string and returns
#' console output, equivalent to \code{eval()} in JavaScript. These
#' functions are stateless: their context is destroyed after the evaluation
#' has completed.
#'
#' @param code A string with JavaScript code
#' @rdname JavaScript
#' @name JavaScript
#' @return Console output.
#' @examples # Evaluate JavaScript code
#' jseval("JSON.stringify({x:Math.random()})")
#' jseval("(function(x){return x+1;})(123)")
#' jseval(c("foo = 123", "bar = 456", "foo + bar"))
#'
#' # Load a library (doesn't do anything yet)
#' underscore <- system.file("js/underscore.js", package="V8")
#' jseval(readLines(underscore))
#'
#' # Cannot define anonymous function in global scope
#' jsvalidate("function(x){2*x}") #FALSE
#' jsvalidate("function foo(x){2*x}") #TRUE
#' jsvalidate("foo = function(x){2*x}") #TRUE
jseval <- function(code) {
    .Call('V8_jseval', PACKAGE = 'V8', code)
}

#' @rdname JavaScript
jsvalidate <- function(code) {
    .Call('V8_jsvalidate', PACKAGE = 'V8', code)
}

make_context <- function() {
    .Call('V8_make_context', PACKAGE = 'V8')
}

