on:
  push:
    branches: [main, master]
  workflow_dispatch:

name: rhel.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#  cancel-in-progress: true

permissions: read-all

jobs:
  rhel:
    runs-on: ubuntu-24.04${{matrix.config.arch=='arm64' && '-arm' || ''}}
    name: ${{ matrix.config.os }} ${{ matrix.config.arch }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: rhel8, arch: 'amd64'}
          - {os: rhel9, arch: 'amd64'}
          - {os: rhel9, arch: 'arm64'}
    container:
      image: ghcr.io/r-hub/containers/${{ matrix.config.os }}:latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-hub/actions/register-redhat@main
        env:
          REDHAT_ORG: ${{ secrets.REDHAT_ORG }}
          REDHAT_KEY: ${{ secrets.REDHAT_KEY }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: '"--no-manual"'
          error-on: '"error"'
        env:
          NOT_CRAN: false
          _R_CHECK_DOC_SIZES_: FALSE
          LANG: en_US.UTF-8
